version: '3.1'
services:
  app:
    container_name: person-role-ms
    image: durpyshark/person-role-ms
    build: ./
    ports:
      - "8082:8082"
    depends_on:
      - person_roles_db_container
  person_roles_db_container:
    image: postgres
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=person_roles_db
    command: -p 5434